openapi: 3.0.0
info:
  title: RAG Knowledge Ingestion API
  version: 1.0.0
  description: API for ingesting and managing RAG knowledge content

paths:
  /ingest:
    post:
      summary: Start the RAG ingestion process
      description: Initiates the process of crawling, extracting, chunking, and storing content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source_urls:
                  type: array
                  items:
                    type: string
                  description: List of URLs to ingest
                chunk_size:
                  type: integer
                  default: 800
                  description: Size of text chunks in words
                overlap:
                  type: integer
                  default: 100
                  description: Overlap between chunks in words
              required:
                - source_urls
      responses:
        '202':
          description: Ingestion process started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                    description: ID of the ingestion job
                  status:
                    type: string
                    enum: [started, processing, completed, failed]
                  message:
                    type: string
                    description: Status message
        '400':
          description: Invalid request parameters
        '500':
          description: Server error during ingestion

  /status/{job_id}:
    get:
      summary: Get ingestion job status
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Job status information
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string
                  status:
                    type: string
                    enum: [started, processing, completed, failed]
                  progress:
                    type: object
                    properties:
                      total_urls:
                        type: integer
                      processed_urls:
                        type: integer
                      total_chunks:
                        type: integer
                      processed_chunks:
                        type: integer
        '404':
          description: Job not found

  /search:
    post:
      summary: Search in the ingested content
      description: Perform similarity search on the ingested content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Search query
                top_k:
                  type: integer
                  default: 5
                  description: Number of results to return
              required:
                - query
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        content:
                          type: string
                        source_url:
                          type: string
                        document_title:
                          type: string
                        chunk_position:
                          type: integer
                        score:
                          type: number
                          format: float
        '500':
          description: Server error during search